# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frakits/Desktop/codename-launcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frakits/Desktop/codename-launcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/frakits/Desktop/codename-launcher/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frakits/Desktop/codename-launcher/CMakeFiles /home/frakits/Desktop/codename-launcher//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frakits/Desktop/codename-launcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/frakits/Desktop/codename-launcher/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named codename_launcher

# Build rule for target.
codename_launcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codename_launcher
.PHONY : codename_launcher

# fast build rule for target.
codename_launcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/build
.PHONY : codename_launcher/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/CMakeFiles/uninstall.dir/build.make _deps/raylib-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build.make _deps/raylib-build/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make _deps/raylib-build/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

src/engine_selector.o: src/engine_selector.cpp.o
.PHONY : src/engine_selector.o

# target to build an object file
src/engine_selector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/engine_selector.cpp.o
.PHONY : src/engine_selector.cpp.o

src/engine_selector.i: src/engine_selector.cpp.i
.PHONY : src/engine_selector.i

# target to preprocess a source file
src/engine_selector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/engine_selector.cpp.i
.PHONY : src/engine_selector.cpp.i

src/engine_selector.s: src/engine_selector.cpp.s
.PHONY : src/engine_selector.s

# target to generate assembly for a file
src/engine_selector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/engine_selector.cpp.s
.PHONY : src/engine_selector.cpp.s

src/global.o: src/global.cpp.o
.PHONY : src/global.o

# target to build an object file
src/global.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/global.cpp.o
.PHONY : src/global.cpp.o

src/global.i: src/global.cpp.i
.PHONY : src/global.i

# target to preprocess a source file
src/global.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/global.cpp.i
.PHONY : src/global.cpp.i

src/global.s: src/global.cpp.s
.PHONY : src/global.s

# target to generate assembly for a file
src/global.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/global.cpp.s
.PHONY : src/global.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/button.o: src/ui/button.cpp.o
.PHONY : src/ui/button.o

# target to build an object file
src/ui/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/button.cpp.o
.PHONY : src/ui/button.cpp.o

src/ui/button.i: src/ui/button.cpp.i
.PHONY : src/ui/button.i

# target to preprocess a source file
src/ui/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/button.cpp.i
.PHONY : src/ui/button.cpp.i

src/ui/button.s: src/ui/button.cpp.s
.PHONY : src/ui/button.s

# target to generate assembly for a file
src/ui/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/button.cpp.s
.PHONY : src/ui/button.cpp.s

src/ui/container.o: src/ui/container.cpp.o
.PHONY : src/ui/container.o

# target to build an object file
src/ui/container.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/container.cpp.o
.PHONY : src/ui/container.cpp.o

src/ui/container.i: src/ui/container.cpp.i
.PHONY : src/ui/container.i

# target to preprocess a source file
src/ui/container.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/container.cpp.i
.PHONY : src/ui/container.cpp.i

src/ui/container.s: src/ui/container.cpp.s
.PHONY : src/ui/container.s

# target to generate assembly for a file
src/ui/container.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/container.cpp.s
.PHONY : src/ui/container.cpp.s

src/ui/object.o: src/ui/object.cpp.o
.PHONY : src/ui/object.o

# target to build an object file
src/ui/object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/object.cpp.o
.PHONY : src/ui/object.cpp.o

src/ui/object.i: src/ui/object.cpp.i
.PHONY : src/ui/object.i

# target to preprocess a source file
src/ui/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/object.cpp.i
.PHONY : src/ui/object.cpp.i

src/ui/object.s: src/ui/object.cpp.s
.PHONY : src/ui/object.s

# target to generate assembly for a file
src/ui/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/object.cpp.s
.PHONY : src/ui/object.cpp.s

src/ui/sprite.o: src/ui/sprite.cpp.o
.PHONY : src/ui/sprite.o

# target to build an object file
src/ui/sprite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/sprite.cpp.o
.PHONY : src/ui/sprite.cpp.o

src/ui/sprite.i: src/ui/sprite.cpp.i
.PHONY : src/ui/sprite.i

# target to preprocess a source file
src/ui/sprite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/sprite.cpp.i
.PHONY : src/ui/sprite.cpp.i

src/ui/sprite.s: src/ui/sprite.cpp.s
.PHONY : src/ui/sprite.s

# target to generate assembly for a file
src/ui/sprite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/sprite.cpp.s
.PHONY : src/ui/sprite.cpp.s

src/ui/text.o: src/ui/text.cpp.o
.PHONY : src/ui/text.o

# target to build an object file
src/ui/text.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/text.cpp.o
.PHONY : src/ui/text.cpp.o

src/ui/text.i: src/ui/text.cpp.i
.PHONY : src/ui/text.i

# target to preprocess a source file
src/ui/text.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/text.cpp.i
.PHONY : src/ui/text.cpp.i

src/ui/text.s: src/ui/text.cpp.s
.PHONY : src/ui/text.s

# target to generate assembly for a file
src/ui/text.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/codename_launcher.dir/build.make CMakeFiles/codename_launcher.dir/src/ui/text.cpp.s
.PHONY : src/ui/text.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... codename_launcher"
	@echo "... glfw"
	@echo "... raylib"
	@echo "... src/engine_selector.o"
	@echo "... src/engine_selector.i"
	@echo "... src/engine_selector.s"
	@echo "... src/global.o"
	@echo "... src/global.i"
	@echo "... src/global.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/button.o"
	@echo "... src/ui/button.i"
	@echo "... src/ui/button.s"
	@echo "... src/ui/container.o"
	@echo "... src/ui/container.i"
	@echo "... src/ui/container.s"
	@echo "... src/ui/object.o"
	@echo "... src/ui/object.i"
	@echo "... src/ui/object.s"
	@echo "... src/ui/sprite.o"
	@echo "... src/ui/sprite.i"
	@echo "... src/ui/sprite.s"
	@echo "... src/ui/text.o"
	@echo "... src/ui/text.i"
	@echo "... src/ui/text.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/frakits/Desktop/codename-launcher/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

